//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JWTTokenBaseSecurityDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Roll_no { get; set; }
        public string Stud_Name { get; set; }
        public string stud_Address { get; set; }
        public int Marks { get; set; }
    }
}
